In [1]:
# efinance validity check
# from 2026.1 to 2026.3
# base info, dialy history for stock and index (include snapmap)

In [2]:
# pip repo
import efinance as ef
import pandas as pd

/Users/xiejz959/miniconda3/envs/quant-cn-a/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
selected_stocks = {
    "601318": "中国平安",
    "600900": "长江电力",
    "601899": "紫金矿业",
}

tracked_indices = {
    "000001": ["上证指数", "上证综指"],
    "000300": ["沪深300", "CSI 300"],
}

beg = "20260101"
end = "20260331"

In [14]:
def inspect_df(df, name="DataFrame"):
    print(f"==== {name} ====")
    if df is None:
        print("Result is None")
        return
    if getattr(df, "empty", True):
        print("DataFrame is empty")
        return
    
    print("shape:", df.shape)
    print("columns:", list(df.columns))
    print("\ndtypes:")
    print(df.dtypes)
    print("\nhead:")
    display(df.head())
    print("\ntail:")
    display(df.tail())
    print("\nmissing values:")
    display(df.isna().sum())

In [5]:
base_601318 = ef.stock.get_base_info("601318")
base_601318

股票代码                    601318
股票名称                      中国平安
净利润             134778000000.0
总市值       1028151912476.099976
流通市值        605278495412.73999
所处行业                       保险Ⅱ
市盈率(动)                    7.63
市净率                       1.03
ROE                       14.0
毛利率                        0.0
净利率                  15.069024
板块编号                    BK0474
dtype: object

In [6]:
for code, name in selected_stocks.items():
    print("=" * 60)
    print(code, name)
    result = ef.stock.get_base_info(code)
    print(type(result))
    print(result)
    print()

============================================================
601318 中国平安
<class 'pandas.Series'>
股票代码                    601318
股票名称                      中国平安
净利润             134778000000.0
总市值       1028151912476.099976
流通市值        605278495412.73999
所处行业                       保险Ⅱ
市盈率(动)                    7.63
市净率                       1.03
ROE                       14.0
毛利率                        0.0
净利率                  15.069024
板块编号                    BK0474
dtype: object

============================================================
600900 长江电力
<class 'pandas.Series'>
股票代码                   600900
股票名称                     长江电力
净利润             34167000000.0
总市值       661620607040.640015
流通市值      661620607040.640015
所处行业                       电力
市盈率(动)                  19.36
市净率                      2.99
ROE                     15.74
毛利率                 62.477197
净利率                 43.436141
板块编号                   BK0428
dtype: object

============================================================
601899 紫金矿业
<class 'pandas.Series'>
股票代码                   601899
股票名称                     紫金矿业
净利润             51777327785.0
总市值       870045516340.799927
流通市值      674090671540.799927
所处行业                     工业金属
市盈率(动)                   16.8
市净率                      4.73
ROE                     33.04
毛利率                  27.72731
净利率                 18.283017
板块编号                   BK1287
dtype: object

In [7]:
hist_601318 = ef.stock.get_quote_history(
    "601318",
    beg=beg,
    end=end,
    klt=101,
    fqt=1,
)
inspect_df(hist_601318, "601318 历史行情")

==== 601318 历史行情 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,中国平安,601318,2026-01-05,69.20,72.36,73.00,69.20,1228831,8.824565e+09,5.56,5.79,3.96,1.15
1,中国平安,601318,2026-01-06,72.40,74.32,74.88,72.40,1468516,1.086752e+10,3.43,2.71,1.96,1.38
2,中国平安,601318,2026-01-07,73.89,73.45,74.70,73.29,919695,6.796568e+09,1.90,-1.17,-0.87,0.86
3,中国平安,601318,2026-01-08,73.37,70.38,73.40,69.66,1685392,1.196959e+10,5.09,-4.18,-3.07,1.58
4,中国平安,601318,2026-01-09,70.60,69.00,71.28,68.24,2063348,1.428574e+10,4.32,-1.96,-1.38,1.94

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,中国平安,601318,2026-03-25,58.50,58.79,59.36,58.42,562389,3.309846e+09,1.62,1.15,0.67,0.53
52,中国平安,601318,2026-03-26,58.78,56.80,58.78,56.53,1011896,5.801815e+09,3.83,-3.38,-1.99,0.95
53,中国平安,601318,2026-03-27,56.86,56.95,57.39,56.42,834379,4.753261e+09,1.71,0.26,0.15,0.78
54,中国平安,601318,2026-03-30,56.34,56.33,56.55,55.84,737544,4.139268e+09,1.25,-1.09,-0.62,0.69
55,中国平安,601318,2026-03-31,56.29,56.78,57.69,56.21,764114,4.363799e+09,2.63,0.80,0.45,0.72

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [8]:
stock_histories = {}

for code, name in selected_stocks.items():
    print("=" * 60)
    print(code, name)
    df = ef.stock.get_quote_history(
        code,
        beg=beg,
        end=end,
        klt=101,
        fqt=1,
    )
    stock_histories[code] = df
    inspect_df(df, f"{code} {name} 历史行情")

============================================================
601318 中国平安
==== 601318 中国平安 历史行情 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,中国平安,601318,2026-01-05,69.20,72.36,73.00,69.20,1228831,8.824565e+09,5.56,5.79,3.96,1.15
1,中国平安,601318,2026-01-06,72.40,74.32,74.88,72.40,1468516,1.086752e+10,3.43,2.71,1.96,1.38
2,中国平安,601318,2026-01-07,73.89,73.45,74.70,73.29,919695,6.796568e+09,1.90,-1.17,-0.87,0.86
3,中国平安,601318,2026-01-08,73.37,70.38,73.40,69.66,1685392,1.196959e+10,5.09,-4.18,-3.07,1.58
4,中国平安,601318,2026-01-09,70.60,69.00,71.28,68.24,2063348,1.428574e+10,4.32,-1.96,-1.38,1.94

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,中国平安,601318,2026-03-25,58.50,58.79,59.36,58.42,562389,3.309846e+09,1.62,1.15,0.67,0.53
52,中国平安,601318,2026-03-26,58.78,56.80,58.78,56.53,1011896,5.801815e+09,3.83,-3.38,-1.99,0.95
53,中国平安,601318,2026-03-27,56.86,56.95,57.39,56.42,834379,4.753261e+09,1.71,0.26,0.15,0.78
54,中国平安,601318,2026-03-30,56.34,56.33,56.55,55.84,737544,4.139268e+09,1.25,-1.09,-0.62,0.69
55,中国平安,601318,2026-03-31,56.29,56.78,57.69,56.21,764114,4.363799e+09,2.63,0.80,0.45,0.72

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

============================================================
600900 长江电力
==== 600900 长江电力 历史行情 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,长江电力,600900,2026-01-05,26.99,27.07,27.10,26.89,765691,2.084118e+09,0.78,0.33,0.09,0.32
1,长江电力,600900,2026-01-06,27.09,27.23,27.23,27.03,738437,2.020308e+09,0.74,0.59,0.16,0.31
2,长江电力,600900,2026-01-07,27.23,27.02,27.24,27.01,721702,1.970227e+09,0.84,-0.77,-0.21,0.30
3,长江电力,600900,2026-01-08,27.02,27.05,27.09,26.98,470573,1.282366e+09,0.41,0.11,0.03,0.20
4,长江电力,600900,2026-01-09,27.06,27.08,27.08,26.97,629035,1.713593e+09,0.41,0.11,0.03,0.26

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,长江电力,600900,2026-03-25,27.15,27.21,27.27,26.92,860545,2.335397e+09,1.29,0.41,0.11,0.35
52,长江电力,600900,2026-03-26,27.19,27.31,27.45,27.10,845014,2.305295e+09,1.29,0.37,0.10,0.35
53,长江电力,600900,2026-03-27,27.28,27.25,27.40,27.18,685517,1.869449e+09,0.81,-0.22,-0.06,0.28
54,长江电力,600900,2026-03-30,27.25,27.14,27.25,27.01,692781,1.880991e+09,0.88,-0.40,-0.11,0.28
55,长江电力,600900,2026-03-31,27.14,27.04,27.33,27.04,802589,2.181329e+09,1.07,-0.37,-0.10,0.33

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

============================================================
601899 紫金矿业
==== 601899 紫金矿业 历史行情 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,紫金矿业,601899,2026-01-05,35.3,35.40,35.64,34.27,3103935,1.087030e+10,3.97,2.70,0.93,1.51
1,紫金矿业,601899,2026-01-06,36.0,37.60,37.70,35.95,3567272,1.319191e+10,4.94,6.21,2.20,1.73
2,紫金矿业,601899,2026-01-07,37.6,36.72,37.70,36.38,3573036,1.319372e+10,3.51,-2.34,-0.88,1.73
3,紫金矿业,601899,2026-01-08,36.2,36.30,37.01,35.79,2415585,8.780063e+09,3.32,-1.14,-0.42,1.17
4,紫金矿业,601899,2026-01-09,36.0,37.22,37.67,35.98,2805790,1.040894e+10,4.66,2.53,0.92,1.36

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,紫金矿业,601899,2026-03-25,33.50,33.24,33.98,33.09,4106152,1.378066e+10,2.76,3.23,1.04,1.99
52,紫金矿业,601899,2026-03-26,33.10,32.09,33.24,31.83,3050473,9.885918e+09,4.24,-3.46,-1.15,1.48
53,紫金矿业,601899,2026-03-27,31.50,32.47,32.72,31.50,2282467,7.382514e+09,3.80,1.18,0.38,1.11
54,紫金矿业,601899,2026-03-30,32.20,32.78,32.80,31.88,2369010,7.676271e+09,2.83,0.95,0.31,1.15
55,紫金矿业,601899,2026-03-31,32.98,32.72,33.50,32.60,2531059,8.352940e+09,2.75,-0.18,-0.06,1.23

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [9]:
required_cols = {"日期", "开盘", "收盘", "最高", "最低"}

for code, df in stock_histories.items():
    print("=" * 60)
    print(code, selected_stocks[code])
    cols = set(df.columns)
    missing = required_cols - cols
    if not missing:
        print("PASS: required columns are present")
    else:
        print("FAIL: missing columns ->", missing)

============================================================
601318 中国平安
PASS: required columns are present
============================================================
600900 长江电力
PASS: required columns are present
============================================================
601899 紫金矿业
PASS: required columns are present

In [10]:
for code, df in stock_histories.items():
    print("=" * 60)
    print(code, selected_stocks[code])
    
    tmp = df.copy()
    tmp["日期"] = pd.to_datetime(tmp["日期"])
    
    print("date min:", tmp["日期"].min())
    print("date max:", tmp["日期"].max())
    print("row count:", len(tmp))
    print("duplicated dates:", tmp["日期"].duplicated().sum())

============================================================
601318 中国平安
date min: 2026-01-05 00:00:00
date max: 2026-03-31 00:00:00
row count: 56
duplicated dates: 0
============================================================
600900 长江电力
date min: 2026-01-05 00:00:00
date max: 2026-03-31 00:00:00
row count: 56
duplicated dates: 0
============================================================
601899 紫金矿业
date min: 2026-01-05 00:00:00
date max: 2026-03-31 00:00:00
row count: 56
duplicated dates: 0

In [11]:
index_snapshot = ef.stock.get_realtime_quotes("沪深系列指数")
inspect_df(index_snapshot, "沪深系列指数 实时快照")

==== 沪深系列指数 实时快照 ====
shape: (1081, 20)
columns: ['股票代码', '股票名称', '涨跌幅', '最新价', '最高', '最低', '今开', '涨跌额', '换手率', '量比', '动态市盈率', '成交量', '成交额', '昨日收盘', '总市值', '流通市值', '行情ID', '市场类型', '更新时间', '最新交易日']

dtypes:
股票代码        str
股票名称        str
涨跌幅      object
最新价      object
最高          str
最低          str
今开          str
涨跌额      object
换手率      object
量比          str
动态市盈率       str
成交量         str
成交额         str
昨日收盘     object
总市值      object
流通市值     object
行情ID        str
市场类型        str
更新时间        str
最新交易日       str
dtype: object

head:

,股票代码,股票名称,涨跌幅,最新价,最高,最低,今开,涨跌额,换手率,量比,动态市盈率,成交量,成交额,昨日收盘,总市值,流通市值,行情ID,市场类型,更新时间,最新交易日
0,000116,信用100,0.01,199.55,-,-,-,0.01,-,-,-,-,-,199.54,-,-,1.000116,沪A,2026-04-01 08:58:45,2026-04-01
1,000022,沪公司债,0.01,255.39,-,-,-,0.02,-,-,-,-,-,255.37,-,-,1.000022,沪A,2026-04-01 08:58:45,2026-04-01
2,000061,沪企债30,0.01,178.59,-,-,-,0.01,-,-,-,-,-,178.58,-,-,1.000061,沪A,2026-04-01 08:58:45,2026-04-01
3,000012,国债指数,0.01,226.11,-,-,-,0.02,-,-,-,-,-,226.09,-,-,1.000012,沪A,2026-04-01 08:58:45,2026-04-01
4,000101,5年信用,0.01,253.51,-,-,-,0.02,-,-,-,-,-,253.49,-,-,1.000101,沪A,2026-04-01 08:58:45,2026-04-01

tail:

,股票代码,股票名称,涨跌幅,最新价,最高,最低,今开,涨跌额,换手率,量比,动态市盈率,成交量,成交额,昨日收盘,总市值,流通市值,行情ID,市场类型,更新时间,最新交易日
1076,000908,300能源,-,-,-,-,-,-,0.0,-,-,-,-,2770.26,4104860955146,4027060918833,1.000908,沪A,2026-04-01 07:55:28,2026-04-01
1077,000907,中证700,-,-,-,-,-,-,0.0,-,-,-,-,6527.31,33517752840201,31299484315702,1.000907,沪A,2026-04-01 07:55:28,2026-04-01
1078,000904,中证200,-,-,-,-,-,-,0.0,-,-,-,-,5625.15,16427421097716,15642768709281,1.000904,沪A,2026-04-01 07:55:28,2026-04-01
1079,000902,中证流通,-,-,-,-,-,-,0.0,-,-,-,-,6206.46,105135554578528,97016907908367,1.000902,沪A,2026-04-01 07:55:28,2026-04-01
1080,000013,企债指数,-,-,-,-,-,-,0.0,-,-,-,-,305.01,-,-,1.000013,沪A,2026-04-01 07:55:28,2026-04-01

missing values:

股票代码     0
股票名称     0
涨跌幅      0
最新价      0
最高       0
最低       0
今开       0
涨跌额      0
换手率      0
量比       0
动态市盈率    0
成交量      0
成交额      0
昨日收盘     0
总市值      0
流通市值     0
行情ID     0
市场类型     0
更新时间     0
最新交易日    0
dtype: int64

In [18]:
index_snapshot[
    index_snapshot["股票名称"].astype(str).isin(["000001", "000300"])
]

Empty DataFrame
Columns: [股票代码, 股票名称, 涨跌幅, 最新价, 最高, 最低, 今开, 涨跌额, 换手率, 量比, 动态市盈率, 成交量, 成交额, 昨日收盘, 总市值, 流通市值, 行情ID, 市场类型, 更新时间, 最新交易日]
Index: []

In [19]:
index_snapshot[
    index_snapshot["股票代码"].astype(str).isin(["000001", "000300"])
]

,股票代码,股票名称,涨跌幅,最新价,最高,最低,今开,涨跌额,换手率,量比,动态市盈率,成交量,成交额,昨日收盘,总市值,流通市值,行情ID,市场类型,更新时间,最新交易日
198,000300,沪深300,0.0,4450.05,-,-,-,0.0,0.0,-,-,-,-,4450.05,52877184970297,50210045304981,1.000300,沪A,2026-04-01 08:58:45,2026-04-01
463,000001,上证指数,0.0,3891.86,-,-,-,0.0,0.0,-,-,-,-,3891.86,63914962743552,59964170185167,1.000001,沪A,2026-04-01 08:58:45,2026-04-01

In [20]:
idx_000001 = ef.stock.get_quote_history(
    "000001",
    beg=beg,
    end=end,
    klt=101,
    fqt=1,
)
inspect_df(idx_000001, "000001 指数历史")

==== 000001 指数历史 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,平安银行,000001,2026-01-05,11.42,11.50,11.51,11.41,875491,1.003479e+09,0.88,0.79,0.09,0.45
1,平安银行,000001,2026-01-06,11.50,11.67,11.68,11.48,1304648,1.512912e+09,1.74,1.48,0.17,0.67
2,平安银行,000001,2026-01-07,11.66,11.64,11.82,11.62,966236,1.131166e+09,1.71,-0.26,-0.03,0.50
3,平安银行,000001,2026-01-08,11.64,11.51,11.65,11.49,1100085,1.268647e+09,1.37,-1.12,-0.13,0.57
4,平安银行,000001,2026-01-09,11.53,11.46,11.53,11.44,983390,1.128077e+09,0.78,-0.43,-0.05,0.51

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,平安银行,000001,2026-03-25,10.89,10.94,10.95,10.79,744780,8.097399e+08,1.47,0.55,0.06,0.38
52,平安银行,000001,2026-03-26,10.91,10.94,11.05,10.90,827664,9.091994e+08,1.37,0.00,0.00,0.43
53,平安银行,000001,2026-03-27,10.91,11.02,11.05,10.83,884129,9.728213e+08,2.01,0.73,0.08,0.46
54,平安银行,000001,2026-03-30,10.98,10.99,11.05,10.94,632522,6.962083e+08,1.00,-0.27,-0.03,0.33
55,平安银行,000001,2026-03-31,11.00,11.08,11.18,10.99,1164565,1.294676e+09,1.73,0.82,0.09,0.60

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [21]:
idx_000300 = ef.stock.get_quote_history(
    "000300",
    beg=beg,
    end=end,
    klt=101,
    fqt=1,
)
inspect_df(idx_000300, "000300 指数历史")

==== 000300 指数历史 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,沪深300,000300,2026-01-05,4661.62,4717.75,4721.64,4661.62,234144839,6.305774e+11,1.30,1.90,87.81,0.71
1,沪深300,000300,2026-01-06,4719.21,4790.69,4790.69,4718.01,296970686,7.254146e+11,1.54,1.55,72.94,0.90
2,沪深300,000300,2026-01-07,4796.93,4776.67,4802.60,4751.07,259095564,6.648979e+11,1.08,-0.29,-14.02,0.78
3,沪深300,000300,2026-01-08,4761.01,4737.65,4765.49,4717.01,238804957,6.306556e+11,1.01,-0.82,-39.02,0.72
4,沪深300,000300,2026-01-09,4725.96,4758.92,4771.43,4719.13,254688038,6.687888e+11,1.10,0.45,21.27,0.77

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,沪深300,000300,2026-03-25,4506.62,4537.47,4542.18,4502.03,262639279,5.504282e+11,0.90,1.40,62.75,0.80
52,沪深300,000300,2026-03-26,4525.33,4477.53,4541.05,4468.96,213736788,4.711275e+11,1.59,-1.32,-59.94,0.65
53,沪深300,000300,2026-03-27,4431.50,4502.57,4519.89,4431.42,192400388,4.405176e+11,1.98,0.56,25.04,0.58
54,沪深300,000300,2026-03-30,4461.74,4491.95,4496.41,4447.14,209293092,4.446295e+11,1.09,-0.24,-10.62,0.63
55,沪深300,000300,2026-03-31,4491.92,4450.05,4523.17,4450.05,224541585,4.845581e+11,1.63,-0.93,-41.90,0.68

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [22]:
idx_sse_name = ef.stock.get_quote_history(
    "上证指数",
    beg=beg,
    end=end,
    klt=101,
    fqt=1,
)
inspect_df(idx_sse_name, "上证指数 历史")

==== 上证指数 历史 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,上证指数,000001,2026-01-05,3986.97,4023.42,4025.26,3983.58,596950455,1.067334e+12,1.05,1.38,54.58,1.24
1,上证指数,000001,2026-01-06,4026.02,4083.67,4083.67,4025.09,702472270,1.175769e+12,1.46,1.50,60.25,1.46
2,上证指数,000001,2026-01-07,4083.84,4085.77,4098.78,4069.44,683384352,1.197423e+12,0.72,0.05,2.10,1.42
3,上证指数,000001,2026-01-08,4077.72,4082.98,4093.87,4067.12,666131337,1.183189e+12,0.65,-0.07,-2.79,1.39
4,上证指数,000001,2026-01-09,4086.76,4120.43,4121.72,4083.62,729837985,1.289206e+12,0.93,0.92,37.45,1.52

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,上证指数,000001,2026-03-25,3892.27,3931.84,3933.06,3891.82,688343626,9.678543e+11,1.06,1.30,50.56,1.43
52,上证指数,000001,2026-03-26,3924.96,3889.08,3937.10,3880.57,615973981,8.483613e+11,1.44,-1.09,-42.76,1.28
53,上证指数,000001,2026-03-27,3852.09,3913.72,3924.11,3852.09,561342963,7.996964e+11,1.85,0.63,24.64,1.17
54,上证指数,000001,2026-03-30,3884.28,3923.29,3924.29,3872.78,595589479,8.398224e+11,1.32,0.24,9.57,1.24
55,上证指数,000001,2026-03-31,3924.07,3891.86,3948.81,3891.86,606704983,8.919453e+11,1.45,-0.80,-31.43,1.26

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [23]:
idx_csi300_name = ef.stock.get_quote_history(
    "沪深300",
    beg=beg,
    end=end,
    klt=101,
    fqt=1,
)
inspect_df(idx_csi300_name, "沪深300 历史")

==== 沪深300 历史 ====
shape: (56, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,沪深300,000300,2026-01-05,4661.62,4717.75,4721.64,4661.62,234144839,6.305774e+11,1.30,1.90,87.81,0.71
1,沪深300,000300,2026-01-06,4719.21,4790.69,4790.69,4718.01,296970686,7.254146e+11,1.54,1.55,72.94,0.90
2,沪深300,000300,2026-01-07,4796.93,4776.67,4802.60,4751.07,259095564,6.648979e+11,1.08,-0.29,-14.02,0.78
3,沪深300,000300,2026-01-08,4761.01,4737.65,4765.49,4717.01,238804957,6.306556e+11,1.01,-0.82,-39.02,0.72
4,沪深300,000300,2026-01-09,4725.96,4758.92,4771.43,4719.13,254688038,6.687888e+11,1.10,0.45,21.27,0.77

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
51,沪深300,000300,2026-03-25,4506.62,4537.47,4542.18,4502.03,262639279,5.504282e+11,0.90,1.40,62.75,0.80
52,沪深300,000300,2026-03-26,4525.33,4477.53,4541.05,4468.96,213736788,4.711275e+11,1.59,-1.32,-59.94,0.65
53,沪深300,000300,2026-03-27,4431.50,4502.57,4519.89,4431.42,192400388,4.405176e+11,1.98,0.56,25.04,0.58
54,沪深300,000300,2026-03-30,4461.74,4491.95,4496.41,4447.14,209293092,4.446295e+11,1.09,-0.24,-10.62,0.63
55,沪深300,000300,2026-03-31,4491.92,4450.05,4523.17,4450.05,224541585,4.845581e+11,1.63,-0.93,-41.90,0.68

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [24]:
beg_long = "20230101"
end_long = "20260401"

In [25]:
stock_histories_long = {}

for code, name in selected_stocks.items():
    print("=" * 60)
    print(code, name)
    df = ef.stock.get_quote_history(
        code,
        beg=beg_long,
        end=end_long,
        klt=101,
        fqt=1,
    )
    stock_histories_long[code] = df
    inspect_df(df, f"{code} {name} 长周期历史行情")

============================================================
601318 中国平安
==== 601318 中国平安 长周期历史行情 ====
shape: (783, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,中国平安,601318,2023-01-03,39.20,39.76,39.87,38.67,602304,2.815200e+09,3.03,0.38,0.15,0.56
1,中国平安,601318,2023-01-04,39.91,41.14,41.24,39.91,869496,4.183125e+09,3.35,3.47,1.38,0.80
2,中国平安,601318,2023-01-05,41.81,41.54,42.11,41.11,737048,3.608715e+09,2.43,0.97,0.40,0.68
3,中国平安,601318,2023-01-06,42.11,42.35,42.44,41.66,780346,3.867149e+09,1.88,1.95,0.81,0.72
4,中国平安,601318,2023-01-09,42.61,43.52,43.56,42.31,881857,4.446813e+09,2.95,2.76,1.17,0.81

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
778,中国平安,601318,2026-03-25,58.50,58.79,59.36,58.42,562389,3.309846e+09,1.62,1.15,0.67,0.53
779,中国平安,601318,2026-03-26,58.78,56.80,58.78,56.53,1011896,5.801815e+09,3.83,-3.38,-1.99,0.95
780,中国平安,601318,2026-03-27,56.86,56.95,57.39,56.42,834379,4.753261e+09,1.71,0.26,0.15,0.78
781,中国平安,601318,2026-03-30,56.34,56.33,56.55,55.84,737544,4.139268e+09,1.25,-1.09,-0.62,0.69
782,中国平安,601318,2026-03-31,56.29,56.78,57.69,56.21,764114,4.363799e+09,2.63,0.80,0.45,0.72

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

============================================================
600900 长江电力
==== 600900 长江电力 长周期历史行情 ====
shape: (783, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,长江电力,600900,2023-01-03,18.12,18.08,18.24,17.97,367992,7.702932e+08,1.49,-0.50,-0.09,0.16
1,长江电力,600900,2023-01-04,18.15,18.00,18.15,17.93,273466,5.703858e+08,1.22,-0.44,-0.08,0.12
2,长江电力,600900,2023-01-05,18.07,17.94,18.14,17.88,439916,9.154978e+08,1.44,-0.33,-0.06,0.19
3,长江电力,600900,2023-01-06,17.93,18.06,18.08,17.74,488491,1.015151e+09,1.90,0.67,0.12,0.21
4,长江电力,600900,2023-01-09,18.11,17.95,18.12,17.87,351344,7.303186e+08,1.38,-0.61,-0.11,0.15

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
778,长江电力,600900,2026-03-25,27.15,27.21,27.27,26.92,860545,2.335397e+09,1.29,0.41,0.11,0.35
779,长江电力,600900,2026-03-26,27.19,27.31,27.45,27.10,845014,2.305295e+09,1.29,0.37,0.10,0.35
780,长江电力,600900,2026-03-27,27.28,27.25,27.40,27.18,685517,1.869449e+09,0.81,-0.22,-0.06,0.28
781,长江电力,600900,2026-03-30,27.25,27.14,27.25,27.01,692781,1.880991e+09,0.88,-0.40,-0.11,0.28
782,长江电力,600900,2026-03-31,27.14,27.04,27.33,27.04,802589,2.181329e+09,1.07,-0.37,-0.10,0.33

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

============================================================
601899 紫金矿业
==== 601899 紫金矿业 长周期历史行情 ====
shape: (783, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,紫金矿业,601899,2023-01-03,8.91,9.48,9.54,8.83,2377424,2.435849e+09,7.93,5.92,0.53,1.16
1,紫金矿业,601899,2023-01-04,9.38,9.25,9.46,9.20,1359564,1.408809e+09,2.74,-2.43,-0.23,0.66
2,紫金矿业,601899,2023-01-05,9.38,9.34,9.45,9.28,1623551,1.689023e+09,1.84,0.97,0.09,0.79
3,紫金矿业,601899,2023-01-06,9.39,9.38,9.45,9.34,1054528,1.103010e+09,1.18,0.43,0.04,0.51
4,紫金矿业,601899,2023-01-09,9.64,10.39,10.41,9.62,3896777,4.360584e+09,8.42,10.77,1.01,1.90

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
778,紫金矿业,601899,2026-03-25,33.50,33.24,33.98,33.09,4106152,1.378066e+10,2.76,3.23,1.04,1.99
779,紫金矿业,601899,2026-03-26,33.10,32.09,33.24,31.83,3050473,9.885918e+09,4.24,-3.46,-1.15,1.48
780,紫金矿业,601899,2026-03-27,31.50,32.47,32.72,31.50,2282467,7.382514e+09,3.80,1.18,0.38,1.11
781,紫金矿业,601899,2026-03-30,32.20,32.78,32.80,31.88,2369010,7.676271e+09,2.83,0.95,0.31,1.15
782,紫金矿业,601899,2026-03-31,32.98,32.72,33.50,32.60,2531059,8.352940e+09,2.75,-0.18,-0.06,1.23

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [26]:
index_histories_long = {}

index_ids = {
    "000001": "上证指数",
    "000300": "沪深300",
}

for code, name in index_ids.items():
    print("=" * 60)
    print(code, name)
    df = ef.stock.get_quote_history(
        code,
        beg=beg_long,
        end=end_long,
        klt=101,
        fqt=1,
    )
    index_histories_long[code] = df
    inspect_df(df, f"{code} {name} 长周期历史行情")

============================================================
000001 上证指数
==== 000001 上证指数 长周期历史行情 ====
shape: (783, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,平安银行,000001,2023-01-03,11.35,11.92,12.00,11.20,2194128,2.971547e+09,7.07,5.39,0.61,1.13
1,平安银行,000001,2023-01-04,11.86,12.47,12.57,11.78,2189683,3.110729e+09,6.63,4.61,0.55,1.13
2,平安银行,000001,2023-01-05,12.55,12.63,12.89,12.52,1665425,2.417272e+09,2.97,1.28,0.16,0.86
3,平安银行,000001,2023-01-06,12.65,12.77,12.87,12.63,1195745,1.747915e+09,1.90,1.11,0.14,0.62
4,平安银行,000001,2023-01-09,12.90,12.95,13.03,12.67,1057659,1.561368e+09,2.82,1.41,0.18,0.55

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
778,平安银行,000001,2026-03-25,10.89,10.94,10.95,10.79,744780,8.097399e+08,1.47,0.55,0.06,0.38
779,平安银行,000001,2026-03-26,10.91,10.94,11.05,10.90,827664,9.091994e+08,1.37,0.00,0.00,0.43
780,平安银行,000001,2026-03-27,10.91,11.02,11.05,10.83,884129,9.728213e+08,2.01,0.73,0.08,0.46
781,平安银行,000001,2026-03-30,10.98,10.99,11.05,10.94,632522,6.962083e+08,1.00,-0.27,-0.03,0.33
782,平安银行,000001,2026-03-31,11.00,11.08,11.18,10.99,1164565,1.294676e+09,1.73,0.82,0.09,0.60

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

============================================================
000300 沪深300
==== 000300 沪深300 长周期历史行情 ====
shape: (783, 13)
columns: ['股票名称', '股票代码', '日期', '开盘', '收盘', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']

dtypes:
股票名称        str
股票代码        str
日期          str
开盘      float64
收盘      float64
最高      float64
最低      float64
成交量       int64
成交额     float64
振幅      float64
涨跌幅     float64
涨跌额     float64
换手率     float64
dtype: object

head:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,沪深300,000300,2023-01-03,3864.84,3887.90,3893.99,3831.25,115051875,2.075402e+11,1.62,0.42,16.27,0.35
1,沪深300,000300,2023-01-04,3886.25,3892.95,3905.90,3873.65,110660743,1.989977e+11,0.83,0.13,5.05,0.34
2,沪深300,000300,2023-01-05,3913.49,3968.58,3974.88,3912.26,116502395,2.563126e+11,1.61,1.94,75.63,0.35
3,沪深300,000300,2023-01-06,3969.55,3980.89,4000.41,3966.47,110953038,2.357443e+11,0.86,0.31,12.31,0.34
4,沪深300,000300,2023-01-09,3998.53,4013.12,4023.09,3990.71,117054425,2.332124e+11,0.81,0.81,32.23,0.35

tail:

,股票名称,股票代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
778,沪深300,000300,2026-03-25,4506.62,4537.47,4542.18,4502.03,262639279,5.504282e+11,0.90,1.40,62.75,0.80
779,沪深300,000300,2026-03-26,4525.33,4477.53,4541.05,4468.96,213736788,4.711275e+11,1.59,-1.32,-59.94,0.65
780,沪深300,000300,2026-03-27,4431.50,4502.57,4519.89,4431.42,192400388,4.405176e+11,1.98,0.56,25.04,0.58
781,沪深300,000300,2026-03-30,4461.74,4491.95,4496.41,4447.14,209293092,4.446295e+11,1.09,-0.24,-10.62,0.63
782,沪深300,000300,2026-03-31,4491.92,4450.05,4523.17,4450.05,224541585,4.845581e+11,1.63,-0.93,-41.90,0.68

missing values:

股票名称    0
股票代码    0
日期      0
开盘      0
收盘      0
最高      0
最低      0
成交量     0
成交额     0
振幅      0
涨跌幅     0
涨跌额     0
换手率     0
dtype: int64

In [27]:
def clean_price_df(df, code_col_name):
    tmp = df.copy()
    
    tmp["日期"] = pd.to_datetime(tmp["日期"])
    
    numeric_cols = ["开盘", "收盘", "最高", "最低", "成交量", "成交额", "涨跌幅", "涨跌额", "换手率"]
    for col in numeric_cols:
        if col in tmp.columns:
            tmp[col] = pd.to_numeric(tmp[col], errors="coerce")
    
    tmp = tmp.sort_values("日期").reset_index(drop=True)
    return tmp

In [28]:
stock_histories_clean = {}

for code, df in stock_histories_long.items():
    stock_histories_clean[code] = clean_price_df(df, "股票代码")
    print(code, selected_stocks[code], stock_histories_clean[code].shape)

601318 中国平安 (783, 13)
600900 长江电力 (783, 13)
601899 紫金矿业 (783, 13)

In [29]:
index_histories_clean = {}

for code, df in index_histories_long.items():
    index_histories_clean[code] = clean_price_df(df, "指数代码")
    print(code, index_ids[code], index_histories_clean[code].shape)

000001 上证指数 (783, 13)
000300 沪深300 (783, 13)

In [30]:
for code, df in stock_histories_clean.items():
    print("=" * 60)
    print(code, selected_stocks[code])
    print("date min:", df["日期"].min())
    print("date max:", df["日期"].max())
    print("rows:", len(df))
    print("duplicated dates:", df["日期"].duplicated().sum())

============================================================
601318 中国平安
date min: 2023-01-03 00:00:00
date max: 2026-03-31 00:00:00
rows: 783
duplicated dates: 0
============================================================
600900 长江电力
date min: 2023-01-03 00:00:00
date max: 2026-03-31 00:00:00
rows: 783
duplicated dates: 0
============================================================
601899 紫金矿业
date min: 2023-01-03 00:00:00
date max: 2026-03-31 00:00:00
rows: 783
duplicated dates: 0

In [31]:
for code, df in index_histories_clean.items():
    print("=" * 60)
    print(code, index_ids[code])
    print("date min:", df["日期"].min())
    print("date max:", df["日期"].max())
    print("rows:", len(df))
    print("duplicated dates:", df["日期"].duplicated().sum())

============================================================
000001 上证指数
date min: 2023-01-03 00:00:00
date max: 2026-03-31 00:00:00
rows: 783
duplicated dates: 0
============================================================
000300 沪深300
date min: 2023-01-03 00:00:00
date max: 2026-03-31 00:00:00
rows: 783
duplicated dates: 0

In [32]:
key_cols = ["日期", "开盘", "收盘", "最高", "最低"]

for code, df in stock_histories_clean.items():
    print("=" * 60)
    print(code, selected_stocks[code])
    print(df[key_cols].isna().sum())

============================================================
601318 中国平安
日期    0
开盘    0
收盘    0
最高    0
最低    0
dtype: int64
============================================================
600900 长江电力
日期    0
开盘    0
收盘    0
最高    0
最低    0
dtype: int64
============================================================
601899 紫金矿业
日期    0
开盘    0
收盘    0
最高    0
最低    0
dtype: int64

In [33]:
for code, df in index_histories_clean.items():
    print("=" * 60)
    print(code, index_ids[code])
    print(df[key_cols].isna().sum())

============================================================
000001 上证指数
日期    0
开盘    0
收盘    0
最高    0
最低    0
dtype: int64
============================================================
000300 沪深300
日期    0
开盘    0
收盘    0
最高    0
最低    0
dtype: int64

In [34]:
def add_moving_averages(df):
    tmp = df.copy()
    tmp["MA20"] = tmp["收盘"].rolling(20).mean()
    tmp["MA60"] = tmp["收盘"].rolling(60).mean()
    tmp["MA120"] = tmp["收盘"].rolling(120).mean()
    tmp["MA250"] = tmp["收盘"].rolling(250).mean()
    return tmp

In [35]:
stock_ma = {}

for code, df in stock_histories_clean.items():
    stock_ma[code] = add_moving_averages(df)
    print("=" * 60)
    print(code, selected_stocks[code])
    display(stock_ma[code][["日期", "收盘", "MA20", "MA60", "MA120", "MA250"]].tail())

============================================================
601318 中国平安

            日期     收盘     MA20       MA60      MA120     MA250
778 2026-03-25  58.79  61.2920  65.572667  62.285000  57.59332
779 2026-03-26  56.80  60.9570  65.377000  62.307083  57.61684
780 2026-03-27  56.95  60.6500  65.168000  62.330000  57.64132
781 2026-03-30  56.33  60.3490  64.956333  62.348833  57.66180
782 2026-03-31  56.78  60.0595  64.722667  62.369167  57.68284

============================================================
600900 长江电力

            日期     收盘     MA20       MA60      MA120     MA250
778 2026-03-25  27.21  27.0565  26.716667  27.269917  27.85784
779 2026-03-26  27.31  27.1200  26.716333  27.272583  27.86104
780 2026-03-27  27.25  27.1805  26.712000  27.275417  27.86432
781 2026-03-30  27.14  27.2090  26.707167  27.275667  27.86784
782 2026-03-31  27.04  27.2125  26.700667  27.275667  27.86924

============================================================
601899 紫金矿业

            日期     收盘     MA20       MA60      MA120     MA250
778 2026-03-25  33.24  35.9565  36.861000  33.238333  25.90800
779 2026-03-26  32.09  35.5925  36.853667  33.299083  25.96844
780 2026-03-27  32.47  35.2385  36.860000  33.360083  26.03148
781 2026-03-30  32.78  34.8390  36.867833  33.419917  26.09356
782 2026-03-31  32.72  34.5320  36.879333  33.478333  26.15424

In [36]:
index_ma = {}

for code, df in index_histories_clean.items():
    index_ma[code] = add_moving_averages(df)
    print("=" * 60)
    print(code, index_ids[code])
    display(index_ma[code][["日期", "收盘", "MA20", "MA60", "MA120", "MA250"]].tail())

============================================================
000001 上证指数

            日期     收盘     MA20       MA60      MA120     MA250
778 2026-03-25  10.94  10.8500  11.089167  11.285750  11.33588
779 2026-03-26  10.94  10.8535  11.079500  11.283500  11.33416
780 2026-03-27  11.02  10.8595  11.070500  11.282500  11.33464
781 2026-03-30  10.99  10.8665  11.061333  11.280083  11.33504
782 2026-03-31  11.08  10.8765  11.053333  11.278917  11.33568

============================================================
000300 沪深300

            日期       收盘       MA20         MA60        MA120       MA250
778 2026-03-25  4537.47  4631.6025  4678.825833  4635.909000  4316.47712
779 2026-03-26  4477.53  4619.1355  4676.591000  4635.705750  4318.36100
780 2026-03-27  4502.57  4608.7315  4674.621667  4635.538750  4320.38412
781 2026-03-30  4491.95  4596.8955  4672.253167  4635.306833  4322.32104
782 2026-03-31  4450.05  4586.6030  4669.045000  4634.340000  4324.08056

In [37]:
def add_returns(df):
    tmp = df.copy()
    tmp["return_20d"] = tmp["收盘"] / tmp["收盘"].shift(20) - 1
    tmp["return_60d"] = tmp["收盘"] / tmp["收盘"].shift(60) - 1
    tmp["return_120d"] = tmp["收盘"] / tmp["收盘"].shift(120) - 1
    return tmp

In [38]:
stock_features = {}

for code, df in stock_ma.items():
    stock_features[code] = add_returns(df)
    print("=" * 60)
    print(code, selected_stocks[code])
    display(
        stock_features[code][
            ["日期", "收盘", "return_20d", "return_60d", "return_120d"]
        ].tail()
    )

============================================================
601318 中国平安

            日期     收盘  return_20d  return_60d  return_120d
778 2026-03-25  58.79   -0.096234   -0.144873     0.082091
779 2026-03-26  56.80   -0.105512   -0.171287     0.048938
780 2026-03-27  56.95   -0.097321   -0.180458     0.050738
781 2026-03-30  56.33   -0.096552   -0.183978     0.041798
782 2026-03-31  56.78   -0.092536   -0.198023     0.044902

============================================================
600900 长江电力

            日期     收盘  return_20d  return_60d  return_120d
778 2026-03-25  27.21    0.047747   -0.015557     0.004059
779 2026-03-26  27.31    0.048771   -0.000732     0.011856
780 2026-03-27  27.25    0.046467   -0.009451     0.012635
781 2026-03-30  27.14    0.021453   -0.010572     0.001107
782 2026-03-31  27.04    0.002595   -0.014218     0.000000

============================================================
601899 紫金矿业

            日期     收盘  return_20d  return_60d  return_120d
778 2026-03-25  33.24   -0.161241    0.068123     0.373554
779 2026-03-26  32.09   -0.184912   -0.013526     0.293952
780 2026-03-27  32.47   -0.179014    0.011842     0.291054
781 2026-03-30  32.78   -0.195977    0.014547     0.280469
782 2026-03-31  32.72   -0.158003    0.021542     0.272657

In [39]:
index_features = {}

for code, df in index_ma.items():
    index_features[code] = add_returns(df)
    print("=" * 60)
    print(code, index_ids[code])
    display(
        index_features[code][
            ["日期", "收盘", "return_20d", "return_60d", "return_120d"]
        ].tail()
    )

============================================================
000001 上证指数

            日期     收盘  return_20d  return_60d  return_120d
778 2026-03-25  10.94    0.007366   -0.058520    -0.020591
779 2026-03-26  10.94    0.006440   -0.050347    -0.024086
780 2026-03-27  11.02    0.011009   -0.046713    -0.010772
781 2026-03-30  10.99    0.012903   -0.047660    -0.025709
782 2026-03-31  11.08    0.018382   -0.041522    -0.012478

============================================================
000300 沪深300

            日期       收盘  return_20d  return_60d  return_120d
778 2026-03-25  4537.47   -0.041897   -0.006723     0.008750
779 2026-03-26  4477.53   -0.052749   -0.029077    -0.005418
780 2026-03-27  4502.57   -0.044172   -0.025572    -0.004431
781 2026-03-30  4491.95   -0.050061   -0.030666    -0.006157
782 2026-03-31  4450.05   -0.044213   -0.041462    -0.025409

In [40]:
sse_df = index_features["000001"][["日期", "收盘"]].rename(columns={"收盘": "上证收盘"})

merged_vs_sse = {}

for code, df in stock_features.items():
    merged = df[["日期", "收盘"]].merge(sse_df, on="日期", how="inner")
    merged["relative_strength_vs_sse"] = merged["收盘"] / merged["上证收盘"]
    merged_vs_sse[code] = merged
    
    print("=" * 60)
    print(code, selected_stocks[code])
    print("merged rows:", len(merged))
    display(merged.tail())

============================================================
601318 中国平安
merged rows: 783

            日期     收盘   上证收盘  relative_strength_vs_sse
778 2026-03-25  58.79  10.94                  5.373857
779 2026-03-26  56.80  10.94                  5.191956
780 2026-03-27  56.95  11.02                  5.167877
781 2026-03-30  56.33  10.99                  5.125569
782 2026-03-31  56.78  11.08                  5.124549

============================================================
600900 长江电力
merged rows: 783

            日期     收盘   上证收盘  relative_strength_vs_sse
778 2026-03-25  27.21  10.94                  2.487203
779 2026-03-26  27.31  10.94                  2.496344
780 2026-03-27  27.25  11.02                  2.472777
781 2026-03-30  27.14  10.99                  2.469518
782 2026-03-31  27.04  11.08                  2.440433

============================================================
601899 紫金矿业
merged rows: 783

            日期     收盘   上证收盘  relative_strength_vs_sse
778 2026-03-25  33.24  10.94                  3.038391
779 2026-03-26  32.09  10.94                  2.933272
780 2026-03-27  32.47  11.02                  2.946461
781 2026-03-30  32.78  10.99                  2.982712
782 2026-03-31  32.72  11.08                  2.953069

In [41]:
csi300_df = index_features["000300"][["日期", "收盘"]].rename(columns={"收盘": "沪深300收盘"})

merged_vs_csi300 = {}

for code, df in stock_features.items():
    merged = df[["日期", "收盘"]].merge(csi300_df, on="日期", how="inner")
    merged["relative_strength_vs_csi300"] = merged["收盘"] / merged["沪深300收盘"]
    merged_vs_csi300[code] = merged
    
    print("=" * 60)
    print(code, selected_stocks[code])
    print("merged rows:", len(merged))
    display(merged.tail())

============================================================
601318 中国平安
merged rows: 783

            日期     收盘  沪深300收盘  relative_strength_vs_csi300
778 2026-03-25  58.79  4537.47                     0.012957
779 2026-03-26  56.80  4477.53                     0.012686
780 2026-03-27  56.95  4502.57                     0.012648
781 2026-03-30  56.33  4491.95                     0.012540
782 2026-03-31  56.78  4450.05                     0.012759

============================================================
600900 长江电力
merged rows: 783

            日期     收盘  沪深300收盘  relative_strength_vs_csi300
778 2026-03-25  27.21  4537.47                     0.005997
779 2026-03-26  27.31  4477.53                     0.006099
780 2026-03-27  27.25  4502.57                     0.006052
781 2026-03-30  27.14  4491.95                     0.006042
782 2026-03-31  27.04  4450.05                     0.006076

============================================================
601899 紫金矿业
merged rows: 783

            日期     收盘  沪深300收盘  relative_strength_vs_csi300
778 2026-03-25  33.24  4537.47                     0.007326
779 2026-03-26  32.09  4477.53                     0.007167
780 2026-03-27  32.47  4502.57                     0.007211
781 2026-03-30  32.78  4491.95                     0.007297
782 2026-03-31  32.72  4450.05                     0.007353